name: Docker Compose Service Deploy

on:
  workflow_call:
    inputs:
      deploy_path:
        required: false
        type: string
        default: /opt/firephenix
      deploy_services:
        required: true
        type: string
    secrets:
      VPS_HOST:
        required: true
      VPS_USER:
        required: true
      VPS_SSH_KEY:
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ inputs.deploy_path }}
            docker compose pull ${{ inputs.deploy_services }}
            docker compose up -d --no-deps ${{ inputs.deploy_services }}
